# CONVERTING DATA STRUCTURES TO ARRAY

In [1]:
import numpy as np

CONVERTING A TUPLE INTO AN ARRAY

In [14]:
tpl=(1,2,3,4)
print(tpl)
print(type(tpl))

print(20*"__")

arr=np.array(tpl)
print(arr)
print(type(arr))

(1, 2, 3, 4)
<class 'tuple'>
________________________________________
[1 2 3 4]
<class 'numpy.ndarray'>


CONVERTING A LIST INTO AN ARRAY

In [15]:
lst=[1,2,3,4,5]
print(lst)
print(type(lst))

print(20*"__")
arr=np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'list'>
________________________________________
[1 2 3 4 5]
<class 'numpy.ndarray'>


CONVERTING A DICTIONARY TO AN ARRAY

In [28]:
dict={1:"dog",2:"cat",3:"horse",4:"Tiger"}
print(dict)
print(type(dict))

print(30*"__")
arr1=np.array(dict.keys())
arr2=np.array(dict.values())

print(arr1)
print(arr2)
print(type(arr1))
print(type(arr2))

{1: 'dog', 2: 'cat', 3: 'horse', 4: 'Tiger'}
<class 'dict'>
____________________________________________________________
dict_keys([1, 2, 3, 4])
dict_values(['dog', 'cat', 'horse', 'Tiger'])
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


CONVERTING SET TO A AN ARRAY

In [38]:
set_={1,2,3,4}
print(set_)
print(type(set_))

print(30*"__")

arr=np.array(set_)
print(arr)
print(type(arr))

{1, 2, 3, 4}
<class 'set'>
____________________________________________________________
{1, 2, 3, 4}
<class 'numpy.ndarray'>


# CONVERTING DATATYPES OF NUMPY ARRAY

CREATE ARRAY OF INTEGERS

In [53]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

print(30*"___")

arr_=arr.astype(float)
print(arr_)
print(type(arr_))

print(30*"___")

arr1=arr.astype("str")
print(arr1)
print(type(arr1))

print(30*"___")
arr1=arr.astype("bool")
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[ True  True  True  True  True]
<class 'numpy.ndarray'>


CREATE AN ARRAY OF FLOATS

In [54]:
arr=np.array([1.,2.,3.,4.,5.])
print(arr)
print(type(arr))

print(30*"___")

arr_=arr.astype(int)
print(arr_)
print(type(arr_))

print(30*"___")

arr1=arr.astype("str")
print(arr1)
print(type(arr1))

print(30*"___")
arr1=arr.astype("bool")
print(arr1)
print(type(arr1))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[1 2 3 4 5]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
['1.0' '2.0' '3.0' '4.0' '5.0']
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[ True  True  True  True  True]
<class 'numpy.ndarray'>


CREATING AN ARRAY OF STRINGS

In [ ]:
arr=np.array(["1","2","3","4"])
print(arr)
print(type(arr))

print(30*"___")

arr_=arr.astype(int)
print(arr_)
print(type(arr_))

print(30*"___")

arr1=arr.astype(float)
print(arr1)
print(type(arr1))

print(30*"___")
arr1=arr.astype("bool")
print(arr1)
print(type(arr1))

['1' '2' '3' '4']
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[1 2 3 4]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[1. 2. 3. 4.]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[ True  True  True  True]
<class 'numpy.ndarray'>


CREATING AN ARRAY OF BOOLEANS

In [58]:
arr=np.array([True,False,False,True,True])
print(arr)
print(type(arr))

print(30*"___")

arr_=arr.astype(int)
print(arr_)
print(type(arr_))

print(30*"___")

arr1=arr.astype(float)
print(arr1)
print(type(arr1))

print(30*"___")
arr1=arr.astype("str")
print(arr1)
print(type(arr1))

[ True False False  True  True]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[1 0 0 1 1]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
[1. 0. 0. 1. 1.]
<class 'numpy.ndarray'>
__________________________________________________________________________________________
['True' 'False' 'False' 'True' 'True']
<class 'numpy.ndarray'>


COPY FUNCTION


In [4]:
lst=[1,3,4,5,6]
print(lst)
lst1=lst
print(lst1)

print(30*"__")
lst[-1]=9
print(lst)
print(lst1)

[1, 3, 4, 5, 6]
[1, 3, 4, 5, 6]
____________________________________________________________
[1, 3, 4, 5, 9]
[1, 3, 4, 5, 9]


In [5]:
lst=[1,3,4,5,6]
print(lst)
lst1=lst.copy()
print(lst1)

print(30*"__")
lst[-1]=9
print(lst)
print(lst1)

[1, 3, 4, 5, 6]
[1, 3, 4, 5, 6]
____________________________________________________________
[1, 3, 4, 5, 9]
[1, 3, 4, 5, 6]
