CREATING A MULTIDMENSIONAL ARRAY

CREATING A 2D ARRAY FROM LISTS OF LIST

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3,4],[2,3,4,5]])

print(arr)

[[1 2 3 4]
 [2 3 4 5]]


CREATING A 3D ARRAY

In [3]:
arr=np.array([[[1,3,4],[1,23,4],[4,5,6]],
      [[1,3,4],[1,23,4],[4,5,6]],
      [[1,3,4],[1,23,4],[4,5,6]]])
print(arr)

[[[ 1  3  4]
  [ 1 23  4]
  [ 4  5  6]]

 [[ 1  3  4]
  [ 1 23  4]
  [ 4  5  6]]

 [[ 1  3  4]
  [ 1 23  4]
  [ 4  5  6]]]


CREATE A 2D ARRAY FROM LIST OF TUPLES


In [4]:
arr=np.array([(1,2,3,4),(2,3,4,5)])

print(arr)

[[1 2 3 4]
 [2 3 4 5]]


CREATE A 2D ARRAY FROM LIST OF ARRAYS

In [7]:
arr=np.array([np.array([1,2,3]),np.array([4,5,6])])
print(arr)

[[1 2 3]
 [4 5 6]]


CREATING A 2D ARRAY FROM A LIST OF STRINGS

In [8]:
arr=np.array([['1','2','3','4'],['2','3','4','5']])

print(arr)

[['1' '2' '3' '4']
 ['2' '3' '4' '5']]


CREATING A 2D ARRAY FROM A LIST OF DICTONARY

In [11]:
arr=np.array([{"1":"dog",2:"cat",3:"horse",4:"TIGER"},{"1":"dog",2:"cat",3:"horse",4:"TIGER"}])
print(arr)


[{'1': 'dog', 2: 'cat', 3: 'horse', 4: 'TIGER'}
 {'1': 'dog', 2: 'cat', 3: 'horse', 4: 'TIGER'}]


# FINDING DETAILS OF AN ARRAY

In [13]:
arr=np.array([[1,2,3,4],[2,3,4,5]])

print(arr.shape)

(2, 4)


PRINTING THE DIMESIONS OF AN ARRAY

In [18]:
arr=np.array([[[1,2,3,4],[2,3,4,5]]])

print(arr.ndim)

3


PRINTING DATATYPE OF AN ARRAY

In [22]:
arr=np.array([[[1,2,3,4],[2,3,4,5]]])

print(arr.dtype)

int64


PRINT THE SIZE OF AN ARRAY

In [23]:
arr=np.array([[[1,2,3,4],[2,3,4,5]]])

print(arr.size)

8


PRINT THE ITEM SIZE || BYTE SIZE TAKEN BY EACH ELEMENT

In [26]:
arr=np.array([[[1,2,3,4,6],[2,3,4,5,9]]])

print(arr.itemsize)

8


PRINT THE TYPE OF ARRAY

In [27]:
arr=np.array([[[1,2,3,4,6],[2,3,4,5,9]]])

print(type(arr))

<class 'numpy.ndarray'>
